### ISSUE TITLE
string field

### ISSUE THREAD

**Issue by ldfloresgon** [solr-express/solr-express#159] opened 2016-10-10 09:55 UTC
when creating a string field appears in Solr as list of strings, someone has encountered this error?
thanks. this is my code:

[SolrField("Message", Indexed = false, Stored = true)]
public string Message { get; set; }

in Solr:
![solr](https://cloud.githubusercontent.com/assets/10603347/19232581/d072a4ac-8ee0-11e6-9bec-913ae275b473.png)

**Comment by diegobrum** [comment] 2016-10-10 11:45
Hi @ldfloresgon 
If you configured **_message field_** in SOLR schema like:

```javascript
<field name="message" multivalue="true" indexed="false" stored="true" />
```
you need configure **_Message property_** in SOLR Document like:

```csharp
[SolrField("Message", Indexed = false, Stored = true)]
public string[] Message { get; set; } // OR public List<string> Message { get; set; }
```

**Comment by ldfloresgon** [comment] 2016-10-10 11:48
hi @diegobrum 
thanks for reply, i configure message field in code like public string but when i add a new document in Solr appears arrays of string, i don't configure in Solr schema, i use "SolrExpress.Solr5": "4.0.2", and solr 6.2.1 thanks

**Comment by ldfloresgon** [comment] 2016-10-10 12:01
@diegobrum i show yo my configuration:

![log](https://cloud.githubusercontent.com/assets/10603347/19235413/edd6927c-8ef1-11e6-8f63-c353a4c81eb2.png)
![startup](https://cloud.githubusercontent.com/assets/10603347/19235417/f06a7468-8ef1-11e6-88e4-ba3b6f5c32d2.png)
![addnewlog](https://cloud.githubusercontent.com/assets/10603347/19235423/f2ec9946-8ef1-11e6-807c-d2642356e99d.png)


thanks

**Comment by diegobrum** [comment] 2016-10-10 13:05
I'll investigate this, asap

**Comment by ldfloresgon** [comment] 2016-10-10 15:21
thanks @diegobrum

**Comment by diegobrum** [comment] 2016-10-13 19:11
Hi @ldfloresgon !

I'm investigating about this issue... but I can't reproduce this error

See below unit test and tell me if it runs ok
**IntegrationTest015** in https://github.com/solr-express/solr-express/blob/master/test/SolrExpress.Solr5.IntegrationTests/IntegrationTests.cs

And, can you show your schema?

**Comment by diegobrum** [comment] 2016-12-14 16:36
Closing for lack of new information

**Closed by diegobrum** 2016-12-14 16:36 UTC
Labels: investigation
